project:
  type: website

website:
  title: "📦 Fundamentals of Package Development"
  navbar:
    background: secondary
    right:
      - icon: github
        href: https://github.com/ateucher/pkg-dev-psc-2024-04-29
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      - sidebar:modules
      - href: materials/slides.pdf
        text: Slides (PDF)
        aria-label: "PDF of slides"
  repo-url: https://github.com/ateucher/pkg-dev-psc-2024-04-29
  repo-actions: [edit, issue]
  sidebar:
    search: true
    id: modules
    title: "Modules"
    style: docked
    background: light
    contents:
      - intro.qmd
      - setup.qmd
      - understanding-pkgs.qmd
      - create-pkg-and-metadata.qmd
      - documentation.qmd
      - testing.qmd
      - dependencies.qmd
      - ci.qmd
      - share.qmd
      
bibliography: references.bib

execute: 
  eval: false

format:
  html:
    theme:
      light:
        - flatly
        - style-light.scss
      dark:
        - darkly
        - style-dark.scss
    toc: true



